--EX1
SELECT MANAGER_ID, COUNT(EMPLOYEE_ID)
FROM EMPLOYEES
GROUP BY MANAGER_ID
HAVING COUNT(EMPLOYEE_ID) > 6
--EX2
SELECT MIN(SALARY) - (MIN(SALARY) * COMISSION_PCT) AS minSalary, MAX(SALARY) - (MAX(SALARY) * COMISSION_PCT) AS maxSalary
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
--EX3
SELECT TOP 1 WITH TIES reg.*, emp.numberOfEmployees
FROM REGIONS AS reg
JOIN COUNTRIES AS cn ON cn.REGION_ID = reg.REGION_ID
JOIN LOCATIONS AS lc ON lc.COUNTRY_ID = cn.COUNTRY_ID
JOIN DEPARTMENTS AS dep ON dep.LOCATION_ID = lc.LOCATION_ID
JOIN (SELECT *, COUNT(EMPLOYEE_ID) AS numberOfEmployees
	  FROM EMPLOYEES
      GROUP BY DEPARTMENT_ID) AS emp ON emp.DEPARTMENT_ID
ORDER BY emp.numberOfEmployees DESC
--EX4
SELECT (avgSalary/AVG(SALARY) - 1) * 100
FROM (SELECT *, AVG(SALARY) AS avgSalary
	  FROM EMPLOYEES)
GROUP BY DEPARTMENT_ID
--EX5
SELECT EMPLOYEE_ID, DEPARTMENT_ID
FROM JOB_HISTORY
WHERE DATEDIFF(YEAR, START_DATE, END_DATE) > 10 OR DATEDIFF(YEAR, START_DATE, GETDATE()) > 10
--EX6
SELECT TOP 10 WITH TIES EMPLOYEE_ID, SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC
EXCEPT 
SELECT TOP 4 WITH TIES EMPLOYEE_ID, SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC;